[pytest]
addopts =
# show summary of all tests that did not pass
    -ra
# Make tracebacks shorter
    --tb=native
testpaths =
    tests
xfail_strict = True
markers =
    requires_nightly: mark test as requiring nightly torchrl/tensordict
