# Logging configuration
experiment_name: acegen
agent_name: sac
log_dir: results
logger_backend: null # csv, wandb, tensorboard, or null
seed: 101

# Environment configuration
num_envs: 10
molscore: /shared/albert/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Collector configuration
total_smiles: 12800
frames_per_batch: 1000
init_random_smiles: 20

# Replay buffer configuration
replay_buffer_size: 10_000

# Architecture configuration
shared_nets: False
prior_actor: gru_chembl_filtered.ckpt
prior_critic: ckpt_240000.pt
vocabulary: chembl_filtered_vocabulary.txt

# Discrete SAC configuration
lr: 0.0001
eps: 1e-06
weight_decay: 0.0
gamma: 0.99
target_update_polyak: 0.995
target_entropy_weight: 0.01
sampled_sequence_length: 20  # Unused
burn_in: 0
batch_size: 64
kl_coef: 0.5
max_grad_norm: 1.0
num_loss_updates: 500
value_loss_function: l2
actor_updates_frequency: 1
