# Logging configuration
experiment_name: acegen
agent_name: dpo
log_dir: results # Directory to save the results
logger_backend: null  # wandb, tensorboard, or null
seed: 101 # multiple seeds can be provided as a list to multiple experiments sequentially e.g. [101, 102, 103]

# Environment configuration
num_envs: 128 # Number of smiles to generate in parallel
total_smiles: 10_000  # Total number of smiles to generate

# Scoring function
molscore_mode: single # single, benchmark, or curriculum
molscore_task: LibINVENT_Exp1:DRD2_SelRF_SubFilt_DF # task configuration (JSON), benchmark (preset only), or curriculum task (preset only)
custom_task: null # Requires molscore_task to be set to null

# Promptsmiles configuration
promptsmiles: N1(*)CCN(CC1)CCCCN(*)
promptsmiles_optimize: True
promptsmiles_shuffle: True
promptsmiles_multi: False

# Model architecture
model: gru # gru, lstm, gpt2, mamba or llama2
# The default prior varies for each model. Refer to the README file in the root directory for more information.
# The default vocabulary varies for each prior. Refer to the README file in the root directory for more information.
custom_model_factory: null # Path to a custom model factory (e.g. my_module.create_model)

# Optimizer configuration
lr: 0.0001
eps: 1.0e-08
weight_decay: 0.0

# DPO configuration
beta: 0.1 # parameter controlling strength of KL penalty
num_mini_batches: 1 # Number of mini-batches to split the collected data into
num_epochs: 1 # Number of times the collected data is reused
